# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Conserts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consert',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
